<div class="container d-flex justify-content-center">
    <div class="card w-100 mt-5" style="max-width: 500px;">
        <div class="card-body p-5">
            <?= $this->flash->output(); ?>

            <form action="<?= $this->url->get('auth/login'); ?>" method="POST">
                <div class="form-group mb-3">
                    <label for="email">Email Address</label>
                    <input type="text" id="email" name="email" class="form-control" placeholder="Enter email">
                </div>

                <div class="form-group mb-3">
                    <label for="password">Password</label>
                    <input type="password" id="password" name="password" class="form-control" placeholder="Password"
                    >
                </div>

                <button type="submit" class="btn btn-primary mt-3 w-100">Sign in</button>
            </form>
        </div>
    </div>
</div>
