<div class="d-flex justify-content-center">
    <div class="card w-100 mt-5" style="max-width: 500px;">
        <div class="card-body p-5">
            <?= $this->flash->output(); ?>

            <form action="<?php
            echo $this->url->get('auth/register'); ?>" method="POST">
                <div class="form-group mt-3">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="text" name="email" class="form-control"
                           placeholder="Enter email">
                </div>
                <div class="form-group mt-3">
                    <label for="exampleInputEmail1">Nickname</label>
                    <input type="text" name="name" class="form-control"
                           placeholder="Enter nickname">
                </div>
                <div class="form-group mt-3">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" name="password" class="form-control" placeholder="Password">
                </div>

                <button type="submit" class="btn btn-primary mt-3">Register</button>
            </form>
        </div>
    </div>
</div>

